# This is a basic workflow to help you get started with Actions

name: Release to VSCode marketplace

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Install VSCE
        run: npm install -g vsce
      - name: Package .vsix file
        run: vsce package
      - name: Publish
        run: vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
